[build]
  command = "npm install -g sass-embedded && bundle install && jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1.0"
  BUNDLER_VERSION = "2.4.0"
  NODE_VERSION = "18"
